# Generated by Django 4.0 on 2021-12-22 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('class_id', models.AutoField(db_column='class_Id', primary_key=True, serialize=False)),
                ('teacher_id', models.IntegerField(blank=True, null=True)),
                ('number_of_students', models.IntegerField()),
                ('cabinet', models.IntegerField()),
                ('class_name', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'class',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Lessons',
            fields=[
                ('lesson_id', models.AutoField(db_column='lesson_Id', primary_key=True, serialize=False)),
                ('lesson_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'lessons',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('position_id', models.AutoField(primary_key=True, serialize=False)),
                ('position', models.CharField(max_length=50)),
                ('pay', models.IntegerField()),
            ],
            options={
                'db_table': 'position',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('schedule_id', models.AutoField(primary_key=True, serialize=False)),
                ('week_day', models.CharField(max_length=30)),
                ('cabinet', models.IntegerField()),
                ('lesson_id', models.IntegerField(blank=True, db_column='lesson_Id', null=True)),
                ('teacher_id', models.IntegerField(blank=True, null=True)),
                ('class_id', models.IntegerField(blank=True, null=True)),
                ('lesson_num', models.IntegerField()),
            ],
            options={
                'db_table': 'schedule',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('school_id', models.AutoField(db_column='school_Id', primary_key=True, serialize=False)),
                ('teacher_id', models.IntegerField(blank=True, db_column='teacher_Id', null=True)),
                ('number_of_classes', models.IntegerField()),
                ('adress', models.CharField(max_length=50)),
                ('speciality', models.CharField(max_length=50)),
                ('email_adress', models.CharField(max_length=50)),
                ('study_level', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'school',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('phone_number', models.IntegerField(blank=True, null=True)),
                ('school_id', models.IntegerField(blank=True, db_column='school_Id', null=True)),
                ('email_adress', models.CharField(blank=True, max_length=30, null=True)),
                ('adress', models.CharField(blank=True, max_length=30, null=True)),
                ('birthday_date', models.CharField(blank=True, max_length=30, null=True)),
                ('student_name', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'student',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('teacher_id', models.AutoField(db_column='teacher_Id', primary_key=True, serialize=False)),
                ('teacher_name', models.CharField(max_length=50)),
                ('lesson_id', models.IntegerField(blank=True, db_column='lesson_Id', null=True)),
                ('phone_number', models.IntegerField()),
                ('email_adress', models.CharField(max_length=50)),
                ('experience', models.IntegerField()),
                ('position', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'teacher',
                'managed': False,
            },
        ),
    ]
